### ISSUE TITLE
Is it possible to implement Node::utf8_text for wasm?

### ISSUE THREAD

**Issue by Enter-tainer** [silvanshade/tree-sitter-facade#34]
Thanks for your great project!
 
Recently, I'm trying to move my application(made with rust and tree-sitter) to wasm. And I found this crate really suitable. But after I managed to make everything work, I found that `utf8_text` function is unimplemented. Is it possible to implement this function?

**Comment by silvanshade** [comment]
Thanks for the kind words.

I think it should be possible to implement. If you look at the existing implementation in the rust crate, it's pretty straightforward:

```rust
    pub fn utf8_text<'a>(&self, source: &'a [u8]) -> Result<&'a str, str::Utf8Error> {
        str::from_utf8(&source[self.start_byte()..self.end_byte()])
    }
```

I can try to add that for the next release.
