### ISSUE TITLE
[Question] Building to WebAssembly

### ISSUE THREAD

**Issue by Sarrus1** [silvanshade/tree-sitter-facade#53]
Hello,

I am new to Rust and I am trying to build a program that uses a tree-sitter parser, and to build everything to WebAssembly.
From what I understand this is not possible because tree-sitter parsers are written in C.
Is this the issue your crate solves? And if it is, are there any drawbacks?

Thanks in advance!

**Comment by Sarrus1** [comment]
For anybody asking themselves the same question, this crate allows you to use tree-sitter in a Rust program and build everything to WebAssembly.

**Comment by silvanshade** [comment]
> Is this the issue your crate solves? And if it is, are there any drawbacks?

@Sarrus1 What this crate is really intended for is to be able to use something very much like the Rust [tree-sitter](https://crates.io/crates/tree-sitter) crate but to be able to target both native or WebAssembly. So yes to the first question, in a sense.

The catch is that you aren't really compiling `tree-sitter` to WASM. Instead I use conditional compilation to select either the native [tree-sitter](https://crates.io/crates/tree-sitter) crate or a wrapper using [wasm-bindgen](https://rustwasm.github.io/wasm-bindgen/) and the [web-tree-sitter](https://www.npmjs.com/package/web-tree-sitter) node package.

The drawbacks are that, although `tree-sitter-facade` tries to provide an interface very close to native `tree-sitter`, it is not exactly the same. Furthermore, some features (particularly having to do with [queries](https://docs.rs/tree-sitter/latest/tree_sitter/struct.Query.html)) are not yet implemented in `tree-sitter-facade`. However, you can access this missing functionality on the WebAssembly side by using [web-tree-sitter-sys](https://github.com/silvanshade/web-tree-sitter-sys) directly.

Here is an example of using `tree-sitter-facade` with `web-tree-sitter-sys` directly (although it requires some `unsafe` coercions, which are actually safe): https://github.com/silvanshade/tower-lsp-web-demo/blob/2c4f00f44f46d98a067150c35119f27ae7d2236c/crates/server/src/handler.rs#L78-L107

Most of the missing functionality can be added and it's just that I haven't had the opportunity to get to it yet.

**Comment by Sarrus1** [comment]
Thanks you very much for your detailed reply!
